### ISSUE TITLE
Create the SubTask Page

### ISSUE THREAD

**Issue by Obixander** [Obixander/SOSUCentre#10]
Add/Create the subtask page where when then user clicks a assignment they get sent to the subtask page

- [x] Create the viewModel
- [x] Create the viewPage
- [x] Create the builder.service needed for viewmodel and viewpage
- [x] Add routing in Appshell.xaml.cs
- [x] Add Binding Context in viewPage.xaml.cs
- [x] Recreate the design in xaml from XD
- [x] Create the namespaces needed in xaml
